server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:aquarium_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:276204}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:super-secret-aquarium-jwt-token-key-2026-min-32-chars-length}
  access-token-expiration-seconds: 86400      # 1 Day
  refresh-token-expiration-seconds: 604800    # 7 Days

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
